periodics:
- name: ci-k8s-infra-build-cluster-prow-build
  cron: "*/5 * * * *" #Every 5 minutes
  cluster: k8s-infra-prow-build
  decorate: true
  max_concurrency: 1
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
  annotations:
    testgrid-dashboards: sig-k8s-infra-prow
    testgrid-tab-name: gke-prow-build-heartbeat
    testgrid-num-failures-to-alert: '6'
    testgrid-alert-email: k8s-infra-alerts@kubernetes.io, k8s-infra-prow-oncall@kubernetes.io
  spec:
    containers:
    - image: gcr.io/k8s-staging-infra-tools/k8s-infra:latest
      command:
      - "echo"
      args:
      - "Everything is fine!"
      resources:
        limits:
          cpu: 100m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 512Mi

- interval: 1h
  name: ci-kubernetes-unit-eks-canary
  annotations:
    testgrid-dashboards: sig-k8s-infra-canaries
    testgrid-tab-name: ci-kubernetes-unit-eks-canary
    testgrid-days-of-results: '1'
    testgrid-create-test-group: 'true'
  decorate: true
  cluster: eks-prow-build-cluster
  extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
  spec:
    # unit tests have no business requiring root or doing privileged operations
    securityContext:
      # NOTE: these are arbitrary non-root values. They don't exist in the
      # image and don't need to, the unit tests should only write to TMPDIR
      runAsUser: 2001
      runAsGroup: 2010
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230406-23cb1879e3-master
        env:
        # set GOMAXPROCS to match the CPU limit.  This informs the Go runtime of the number of
        # compile jobs/tests to run in parallel.
        - name: GOMAXPROCS
          value: "4"
        securityContext:
          allowPrivilegeEscalation: false
        command:
          - make
          - test
        # TODO: direct copy from pull-kubernetes-bazel-test, tune these
        resources:
          limits:
            cpu: 4
            memory: "36Gi"
          requests:
            cpu: 4
            memory: "36Gi"

- interval: 1h
  cluster: eks-prow-build-cluster
  name: ci-kubernetes-kind-e2e-parallel-eks-canary
  annotations:
    testgrid-dashboards: sig-k8s-infra-canaries
    testgrid-tab-name: kind-master-parallel-eks-canary
    description: Uses kubetest to run e2e tests against a latest kubernetes master cluster created with sigs.k8s.io/kind
    testgrid-num-columns-recent: '6'
    fork-per-release: "true"
    fork-per-release-periodic-interval: 1h 2h 6h 24h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  decorate: true
  decoration_config:
    timeout: 60m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/krte:v20230406-23cb1879e3-master
      command:
      - wrapper.sh
      - bash
      - -c
      - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && e2e-k8s.sh
      env:
      - name: FOCUS
        value: "."
      # TODO(bentheelder): reduce the skip list further
      - name: SKIP
        value: \[Slow\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|PodSecurityPolicy|LoadBalancer|load.balancer|In-tree.Volumes.\[Driver:.nfs\]|PersistentVolumes.NFS|Network.should.set.TCP.CLOSE_WAIT.timeout|Simple.pod.should.support.exec.through.an.HTTP.proxy|subPath.should.support.existing|should.provide.basic.identity
      - name: PARALLEL
        value: "true"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        limits:
          memory: 9Gi
          cpu: 7
        requests:
          # these are both a bit below peak usage during build
          # this is mostly for building kubernetes
          memory: 9Gi
          cpu: 7

- interval: 1h
  cluster: eks-prow-build-cluster
  name: ci-kubernetes-verify-master-eks-canary
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  annotations:
    fork-per-release: "true"
    fork-per-release-periodic-interval: 2h 2h 6h 24h
    testgrid-dashboards: sig-k8s-infra-canaries
    testgrid-tab-name: verify-master-eks-canary
    description: "Ends up running: make verify"
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230406-23cb1879e3-master
      imagePullPolicy: Always
      command:
      - runner.sh
      args:
      - ./hack/jenkins/verify-dockerized.sh
      env:
      - name: EXCLUDE_READONLY_PACKAGE
        value: "y"
      - name: KUBE_VERIFY_GIT_BRANCH
        value: master
      - name: REPO_DIR
        value: /workspace/k8s.io/kubernetes
      # Consider removing after https://github.com/golang/go/issues/49035 is solved
      # See https://github.com/kubernetes/kubernetes/pull/108618
      - name: TYPECHECK_SERIAL
        value: "true"
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
      resources:
        limits:
          cpu: 6
          memory: 24Gi
        requests:
          cpu: 6
          memory: 24Gi

- interval: 1h
  cluster: eks-prow-build-cluster
  name: ci-kubernetes-integration-master-eks-canary
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  annotations:
    fork-per-release: "true"
    fork-per-release-periodic-interval: 2h 2h 6h 24h
    testgrid-dashboards: sig-k8s-infra-canaries
    testgrid-tab-name: integration-master-eks-canary
    description: "Ends up running: make test-cmd test-integration"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230406-23cb1879e3-master
      command:
      - runner.sh
      args:
      - ./hack/jenkins/test-dockerized.sh
      env:
      - name: SHORT
        value: --short=false
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
      resources:
        limits:
          cpu: 6
          memory: 20Gi
        requests:
          cpu: 6
          memory: 20Gi

- name: ci-benchmark-scheduler-perf-master-eks-canary
  cluster: eks-prow-build-cluster
  tags:
  - "perfDashPrefix: scheduler-perf-benchmark"
  - "perfDashJobType: benchmark"
  interval: 2h30m
  annotations:
    testgrid-dashboards: sig-k8s-infra-canaries
    testgrid-tab-name: scheduler-perf-eks-canary
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  decoration_config:
    timeout: 2h25m
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230406-23cb1879e3-master
      command:
      - ./hack/jenkins/benchmark-dockerized.sh
      args:
      - ./test/integration/scheduler_perf
      env:
      - name: KUBE_TIMEOUT
        value: --timeout=2h25m
      - name: TEST_PREFIX
        value: BenchmarkPerfScheduling
      # Set the benchtime to a very low value so every test is ran at most once
      # even on very powerful machines
      - name: BENCHTIME
        value: 1ns
      # We need to constraint compute resources so all the tests
      # finish approximately at the same time. More compute power
      # can increase scheduling throughput and make consequent results
      # incomparable.
      resources:
        requests:
          cpu: 6
          memory: "24Gi"
        limits:
          cpu: 6
          memory: "24Gi"

- interval: 1h
  cluster: eks-prow-build-cluster
  # This combines tests from ci-kubernetes-kind-conformance and sig-storage
  # and runs them with JSON output in all components which support that.
  # Also enables contextual logging and (to get more coverage) dynamic
  # resource allocation.
  name: ci-kubernetes-kind-e2e-json-logging-eks-canary
  annotations:
    testgrid-dashboards: sig-k8s-infra-canaries
    testgrid-tab-name: kind-json-logging-master-eks-canary
    description: Conformance and storage tests with JSON logging enabled using sigs.k8s.io/kind
    testgrid-num-columns-recent: '6'
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  decorate: true
  decoration_config:
    timeout: 150m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/krte:v20230406-23cb1879e3-master
      command:
      - wrapper.sh
      - bash
      - -c
      # The modified e2e-k8s.sh with support for FEATURE_GATES and RUNTIME_CONFIG comes from
      # https://github.com/kubernetes-sigs/kind/pull/3023. Once that PR is merged and a
      # kind release is done, pulling it separately via curl can be removed.
      - >
        curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" &&
        curl -sSL https://github.com/pohly/kind/raw/e2e-feature-gates/hack/ci/e2e-k8s.sh >$(which e2e-k8s.sh) &&
        chmod u+x $(which e2e-k8s.sh) &&
        e2e-k8s.sh

      env:
      # Options from https://github.com/kubernetes-sigs/kind/blob/d1eecc46e30cac9d35cd32dc52677ef75ec22e18/hack/ci/e2e-k8s.sh#L79-L83
      - name: CLUSTER_LOG_FORMAT
        value: json
      - name: GOMAXPROCS
        value: "7"
      - name: KIND_CLUSTER_LOG_LEVEL
        # Default is 4, but we want to exercise more log calls and get more output.
        value: "10"
      - name: FEATURE_GATES
        value: '{"DynamicResourceAllocation":true,"ContextualLogging":true}'
      - name: RUNTIME_CONFIG
        value: '{"resource.k8s.io/v1alpha2":"true"}'
      # don't retry conformance tests
      - name: GINKGO_TOLERATE_FLAKES
        value: "n"
      - name: FOCUS
        value: \[Conformance\]|\[Driver:.csi-hostpath\]|DynamicResourceAllocation
      # TODO(bentheelder): reduce the skip list further
      # NOTE: this skip list is from the standard periodic kind job, just to ensure
      # we don't accidentally select any of these
      - name: SKIP
        value: \[Slow\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|PodSecurityPolicy|LoadBalancer|load.balancer|In-tree.Volumes.\[Driver:.nfs\]|PersistentVolumes.NFS|Network.should.set.TCP.CLOSE_WAIT.timeout|Simple.pod.should.support.exec.through.an.HTTP.proxy|subPath.should.support.existing|should.provide.basic.identity
      - name: PARALLEL
        value: "true"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        limits:
          memory: 9Gi
          cpu: 7
        requests:
          # these are both a bit below peak usage during build
          # this is mostly for building kubernetes
          memory: 9Gi
          cpu: 7
